version: "3.8"

services:
  scaler:
    image: scaler
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
