version: "3.8"

services:
  agent:
    image: portainer/agent
    environment:
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ce
    command:
      - --host=tcp://tasks.agent:9001
      - --tlsskipverify
      - --admin-password-file=/run/secrets/portainer_pass
    volumes:
      - portainer_data:/data
    secrets:
      - portainer_pass
    networks:
      - agent_network
      - proxy_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
        - traefik.http.routers.portainer.entrypoints=http
        - traefik.http.routers.portainer.service=portainer-s
        - traefik.http.services.portainer-s.loadbalancer.server.port=9000

networks:
  agent_network:
    driver: overlay
    attachable: true
  proxy_public:
    external: true

volumes:
  portainer_data: {}

secrets:
  portainer_pass:
    file: portainer-pass
